# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: myDjango

channels:
- conda-forge
- defaults

dependencies:
- python

# system dependencies


# database dependencies


# plotting dependencies

